### PR TITLE
Move API to api folder

### PR DESCRIPTION
**Pull request by sfriedowitz**
A straight refactor, moving the top-level interfaces into their own `api` folder. The only code update is in `learners.py` to correct a path calling `TrainingRow.build`.

### CODE REVIEW

**Comment by sfriedowitz** [comment]
Failed due to some dependency download issue...rebuilding

**Comment by StevenKauwe** [comment]
@sfriedowitz, looks like the rebuild succeeded this time. :D

**Comment by sfriedowitz** [comment]
@StevenKauwe it did indeed...so this seems ready to merge pending your approval 😉

**Review by StevenKauwe — APPROVED** [review]
LGTM.
quick question. where do these live?
`io.citrine.lolo.{DataGenerator, SeedRandomMixIn, etc.}`

**Comment by sfriedowitz** [comment]
>quick question. where do these live?
>io.citrine.lolo.{DataGenerator, SeedRandomMixIn, etc.}

These are in the test code. So instead of `src/main`, they are in `src/test`, but the package path is mimicked on both sides.

**Pull request merged**
